---
redis:
  service_name: my-redis
  service_id: 12345abcde
  dedicated_vm_plan_id: id-for-dedicated-vm-plan
  shared_vm_plan_id: id-for-shared-vm-plan
  host: example.com
  data_directory: /tmp/redis/data/directory
  log_directory: /tmp/redis/log/directory
  redis_conf_path: /tmp/to/redis/config.conf
  process_check_interval: 5
  start_redis_timeout: 3
  service_instance_limit: 3
  serviceKeysSupported: true
  dedicated:
    nodes:
      - 10.0.0.1
      - 10.0.0.2
      - 10.0.0.3
    port: 6379
    statefile_path: "/tmp/redis-config-dir/statefile.json"
auth:
  username: admin
  password: secret

backend_host: localhost
backend_port: 3000
agent_port: 1234

monit_executable_path: /some/path/to/monit
redis_server_executable_path: /some/path/to/redis-server
